### ISSUE TITLE
[demo-agent] imagePullSecrets is not used for azpAgentContainer

### ISSUE THREAD

**Issue by 24mu13** [MShekow/azure-pipelines-k8s-agent-scaler#36]
Is there any other key for referencing a secret for azpAgentContainer image pulling?

**Comment by MShekow** [comment]
imagePullSecrets are defined for _Pods_ (not _containers_). See here: https://github.com/MShekow/azure-pipelines-k8s-agent-scaler/blob/b74f83a805455e3af972d4bab82a3d1409fa6f9f/demo-charts/demo-agent/templates/v1_autoscaledagent.yaml#L35-L37

If your Kubernetes cluster does not use it for that azpAgentContainer, something is seriously wrong with your cluster.
