### ISSUE TITLE
Doc: docker in docker restriction

### ISSUE THREAD

**Issue by 24mu13** [MShekow/azure-pipelines-k8s-agent-scaler#38]
Would be nice to document that any docker based task will not work because of the containerd limitation - see [Use Azure Kubernetes Service cluster](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#use-docker-within-a-docker-container).

Also if there is any alternative solution, could be listed in that documentation.

BTW: congrats for the very good work!

**Comment by MShekow** [comment]
Thanks for reporting it. See https://github.com/MShekow/azure-pipelines-k8s-agent-scaler/commit/c6dbb5bd17ba0c758f6a8cb8390ae255376e1f63

**Comment by 24mu13** [comment]
Thank you very much @MShekow: I didn't pay necessary attention to the par. [2](https://www.augmentedmind.de/2023/12/10/azure-pipelines-agents-kubernetes-operator/#2-static-sidecar-containers); does it mean I can define my Docker static sidecar to also run the AZP [Docker task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-v2?view=azure-pipelines&tabs=yaml)? Or could I only achieve same result (e.g. building/pushing Docker image) by scripting instead?

**Comment by MShekow** [comment]
> Thank you very much @MShekow: I didn't pay necessary attention to the par. [2](https://www.augmentedmind.de/2023/12/10/azure-pipelines-agents-kubernetes-operator/#2-static-sidecar-containers); does it mean I can define my Docker static sidecar to also run the AZP [Docker task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-v2?view=azure-pipelines&tabs=yaml)? Or could I only achieve same result (e.g. building/pushing Docker image) by scripting instead?

I doubt that this would work. The Docker task seems really expect a _locally-running_ Docker daemon (there is no configuration option to specify a docker daemon socket address for the Docker task).

The questions is: what do you want to use the docker task for? If you want to _build_ images, just use BuildKit, as explained in the tutorial. If you want to _run_ images, just define them as `ExtraAgentContainers`.
