### ISSUE TITLE
Feat: multiple CRs on same namespace

### ISSUE THREAD

**Issue by 24mu13** [MShekow/azure-pipelines-k8s-agent-scaler#46]
I would like to scale up/down various agent pools within the same Kubernetes namespace.
Currently I wasn't able to achieve that, so I offer this as additional feature..

**Comment by MShekow** [comment]
I currently don't have time to look into it, but if what you say is correct, it's not a _feature_ but a _bug_. It was always my intention to allow multiple CRs in the same namespace (as long as they address a different _agent pool_).

**Comment by 24mu13** [comment]
True, I double checked: I had this effect, but for another reason.
